version: "3"
services:
  postgres:
    image: postgres:16-alpine
    container_name: jooq-spring-example-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
